import type { PrismaClient } from '@prisma/client';
import { logger as defaultLogger } from './logger';

type LoggerLike = Pick<typeof defaultLogger, 'info' | 'error'>;

const DDL_STATEMENTS = [
    `ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "creatorSettlementWallet" TEXT;`,
    `ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "creatorRewardWallet" TEXT;`,
    `ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "creatorFundingWallet" TEXT;`,
    `ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "rollupMode" TEXT;`,
    `ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "fixtureId" TEXT;`,
    `ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "marketType" TEXT;`,
    `ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "selection" TEXT;`,
    `CREATE INDEX IF NOT EXISTS "Offer_fixtureId_rollupMode_idx" ON "Offer"("fixtureId", "rollupMode");`,
    `UPDATE "Offer" SET "rollupMode" = 'ER' WHERE "rollupMode" IS NULL;`,
    `ALTER TABLE "Offer" ALTER COLUMN "rollupMode" SET DEFAULT 'ER';`,
    `ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "rollupMode" TEXT;`,
    `UPDATE "Ticket" SET "rollupMode" = 'ER' WHERE "rollupMode" IS NULL;`,
    `ALTER TABLE "Ticket" ALTER COLUMN "rollupMode" SET DEFAULT 'ER';`,
    `ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "webhookEvents" TEXT;`,
    `CREATE TABLE IF NOT EXISTS "AgentEvent" (
        "id" TEXT NOT NULL,
        "wallet" TEXT NOT NULL,
        "event" TEXT NOT NULL,
        "ticketId" TEXT,
        "dealId" TEXT,
        "payload" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "deliveredAt" TIMESTAMP(3),
        "ackedAt" TIMESTAMP(3),
        "expiresAt" TIMESTAMP(3) NOT NULL,
        CONSTRAINT "AgentEvent_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE INDEX IF NOT EXISTS "AgentEvent_wallet_ackedAt_createdAt_idx" ON "AgentEvent"("wallet", "ackedAt", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "AgentEvent_wallet_event_createdAt_idx" ON "AgentEvent"("wallet", "event", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "AgentEvent_expiresAt_idx" ON "AgentEvent"("expiresAt");`,
    `CREATE TABLE IF NOT EXISTS "AgentNotificationChannel" (
        "id" TEXT NOT NULL,
        "wallet" TEXT NOT NULL,
        "type" TEXT NOT NULL,
        "enabled" BOOLEAN NOT NULL DEFAULT true,
        "events" TEXT,
        "config" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "lastSentAt" TIMESTAMP(3),
        "lastError" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "AgentNotificationChannel_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE INDEX IF NOT EXISTS "AgentNotificationChannel_wallet_enabled_idx" ON "AgentNotificationChannel"("wallet", "enabled");`,
    `CREATE INDEX IF NOT EXISTS "AgentNotificationChannel_wallet_type_idx" ON "AgentNotificationChannel"("wallet", "type");`,
    `CREATE TABLE IF NOT EXISTS "AgentStrategyTemplate" (
        "id" TEXT NOT NULL,
        "wallet" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "description" TEXT,
        "enabled" BOOLEAN NOT NULL DEFAULT true,
        "defaults" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "AgentStrategyTemplate_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "AgentStrategyTemplate_wallet_name_key" ON "AgentStrategyTemplate"("wallet", "name");`,
    `CREATE INDEX IF NOT EXISTS "AgentStrategyTemplate_wallet_enabled_idx" ON "AgentStrategyTemplate"("wallet", "enabled");`,
    `CREATE INDEX IF NOT EXISTS "AgentStrategyTemplate_wallet_updatedAt_idx" ON "AgentStrategyTemplate"("wallet", "updatedAt");`,
    `CREATE TABLE IF NOT EXISTS "ArenaFixture" (
        "id" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "sport" TEXT NOT NULL DEFAULT 'football',
        "homeTeam" TEXT,
        "awayTeam" TEXT,
        "startsAt" TIMESTAMP(3),
        "status" TEXT NOT NULL DEFAULT 'unknown',
        "raw" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ArenaFixture_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "ArenaFixture_fixtureId_key" ON "ArenaFixture"("fixtureId");`,
    `CREATE INDEX IF NOT EXISTS "ArenaFixture_status_startsAt_idx" ON "ArenaFixture"("status", "startsAt");`,
    `CREATE TABLE IF NOT EXISTS "ArenaOddsUpdate" (
        "id" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "market" TEXT NOT NULL,
        "selection" TEXT NOT NULL,
        "odds" DOUBLE PRECISION NOT NULL,
        "impliedProbability" DOUBLE PRECISION,
        "source" TEXT NOT NULL,
        "sourceUpdateId" TEXT,
        "sourceTimestamp" TIMESTAMP(3) NOT NULL,
        "raw" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ArenaOddsUpdate_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE INDEX IF NOT EXISTS "ArenaOddsUpdate_fixtureId_market_selection_sourceTimestamp_idx" ON "ArenaOddsUpdate"("fixtureId", "market", "selection", "sourceTimestamp");`,
    `CREATE INDEX IF NOT EXISTS "ArenaOddsUpdate_sourceUpdateId_idx" ON "ArenaOddsUpdate"("sourceUpdateId");`,
    `CREATE TABLE IF NOT EXISTS "ArenaScoreUpdate" (
        "id" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "homeScore" INTEGER,
        "awayScore" INTEGER,
        "status" TEXT NOT NULL DEFAULT 'unknown',
        "source" TEXT NOT NULL,
        "sourceUpdateId" TEXT,
        "sourceTimestamp" TIMESTAMP(3) NOT NULL,
        "raw" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ArenaScoreUpdate_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE INDEX IF NOT EXISTS "ArenaScoreUpdate_fixtureId_sourceTimestamp_idx" ON "ArenaScoreUpdate"("fixtureId", "sourceTimestamp");`,
    `CREATE INDEX IF NOT EXISTS "ArenaScoreUpdate_sourceUpdateId_idx" ON "ArenaScoreUpdate"("sourceUpdateId");`,
    `CREATE TABLE IF NOT EXISTS "ArenaTimelineEvent" (
        "id" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "eventType" TEXT NOT NULL,
        "homeTeam" TEXT,
        "awayTeam" TEXT,
        "marketType" TEXT,
        "selection" TEXT,
        "oddsValue" DOUBLE PRECISION,
        "scoreState" JSONB,
        "txlineTimestamp" TIMESTAMP(3) NOT NULL,
        "sourceEndpoint" TEXT NOT NULL,
        "sourceUpdateId" TEXT,
        "dedupeKey" TEXT NOT NULL,
        "raw" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ArenaTimelineEvent_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "ArenaTimelineEvent_dedupeKey_key" ON "ArenaTimelineEvent"("dedupeKey");`,
    `CREATE INDEX IF NOT EXISTS "ArenaTimelineEvent_fixtureId_txlineTimestamp_eventType_idx" ON "ArenaTimelineEvent"("fixtureId", "txlineTimestamp", "eventType");`,
    `CREATE INDEX IF NOT EXISTS "ArenaTimelineEvent_sourceEndpoint_txlineTimestamp_idx" ON "ArenaTimelineEvent"("sourceEndpoint", "txlineTimestamp");`,
    `CREATE TABLE IF NOT EXISTS "ArenaStrategySignal" (
        "id" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "strategy" TEXT NOT NULL,
        "signalType" TEXT NOT NULL,
        "marketType" TEXT,
        "selection" TEXT,
        "direction" TEXT NOT NULL,
        "confidence" DOUBLE PRECISION NOT NULL,
        "oddsBefore" DOUBLE PRECISION,
        "oddsAfter" DOUBLE PRECISION,
        "oddsChangePct" DOUBLE PRECISION,
        "impliedBefore" DOUBLE PRECISION,
        "impliedAfter" DOUBLE PRECISION,
        "impliedDelta" DOUBLE PRECISION,
        "scoreContext" JSONB,
        "tradeIntent" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "reason" TEXT NOT NULL,
        "sourceEventIds" JSONB NOT NULL DEFAULT '[]'::jsonb,
        "signalTimestamp" TIMESTAMP(3) NOT NULL,
        "dedupeKey" TEXT NOT NULL,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ArenaStrategySignal_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "ArenaStrategySignal_dedupeKey_key" ON "ArenaStrategySignal"("dedupeKey");`,
    `CREATE INDEX IF NOT EXISTS "ArenaStrategySignal_fixtureId_strategy_signalTimestamp_idx" ON "ArenaStrategySignal"("fixtureId", "strategy", "signalTimestamp");`,
    `CREATE INDEX IF NOT EXISTS "ArenaStrategySignal_strategy_confidence_idx" ON "ArenaStrategySignal"("strategy", "confidence");`,
    `CREATE TABLE IF NOT EXISTS "ArenaStrategyOffer" (
        "id" TEXT NOT NULL,
        "signalId" TEXT NOT NULL,
        "offerId" TEXT NOT NULL,
        "wallet" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "params" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "dedupeKey" TEXT NOT NULL,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ArenaStrategyOffer_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "ArenaStrategyOffer_dedupeKey_key" ON "ArenaStrategyOffer"("dedupeKey");`,
    `CREATE INDEX IF NOT EXISTS "ArenaStrategyOffer_signalId_idx" ON "ArenaStrategyOffer"("signalId");`,
    `CREATE INDEX IF NOT EXISTS "ArenaStrategyOffer_offerId_idx" ON "ArenaStrategyOffer"("offerId");`,
    `CREATE INDEX IF NOT EXISTS "ArenaStrategyOffer_wallet_createdAt_idx" ON "ArenaStrategyOffer"("wallet", "createdAt");`,
    `CREATE TABLE IF NOT EXISTS "ArenaOutcome" (
        "id" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "status" TEXT NOT NULL,
        "homeScore" INTEGER NOT NULL,
        "awayScore" INTEGER NOT NULL,
        "winner" TEXT NOT NULL,
        "source" TEXT NOT NULL,
        "sourceUpdateId" TEXT,
        "sourceTimestamp" TIMESTAMP(3) NOT NULL,
        "settledAt" TIMESTAMP(3) NOT NULL,
        "raw" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ArenaOutcome_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "ArenaOutcome_fixtureId_key" ON "ArenaOutcome"("fixtureId");`,
    `CREATE INDEX IF NOT EXISTS "ArenaOutcome_winner_idx" ON "ArenaOutcome"("winner");`,
    `CREATE INDEX IF NOT EXISTS "ArenaOutcome_sourceTimestamp_idx" ON "ArenaOutcome"("sourceTimestamp");`,
    `CREATE TABLE IF NOT EXISTS "ArenaMatch" (
        "id" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "signalId" TEXT,
        "strategy" TEXT,
        "marketType" TEXT,
        "selection" TEXT,
        "direction" TEXT,
        "signalConfidence" DOUBLE PRECISION,
        "makerWallet" TEXT NOT NULL,
        "takerWallet" TEXT,
        "buyerWallet" TEXT,
        "sellerWallet" TEXT,
        "offerId" TEXT,
        "ticketId" TEXT,
        "escrowPda" TEXT,
        "rollupMode" TEXT NOT NULL DEFAULT 'NONE',
        "status" TEXT NOT NULL DEFAULT 'created',
        "buyerDepositLamports" TEXT,
        "sellerDepositLamports" TEXT,
        "buyerDepositTx" TEXT,
        "sellerDepositTx" TEXT,
        "buyerDepositedAt" TIMESTAMP(3),
        "sellerDepositedAt" TIMESTAMP(3),
        "outcomeId" TEXT,
        "outcomeWinner" TEXT,
        "winnerWallet" TEXT,
        "settlementAction" TEXT,
        "settlementStatus" TEXT,
        "releaseTx" TEXT,
        "refundTx" TEXT,
        "settledAt" TIMESTAMP(3),
        "proof" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "lastError" TEXT,
        "startedAt" TIMESTAMP(3),
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ArenaMatch_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE INDEX IF NOT EXISTS "ArenaMatch_fixtureId_status_idx" ON "ArenaMatch"("fixtureId", "status");`,
    `CREATE INDEX IF NOT EXISTS "ArenaMatch_signalId_idx" ON "ArenaMatch"("signalId");`,
    `CREATE INDEX IF NOT EXISTS "ArenaMatch_offerId_idx" ON "ArenaMatch"("offerId");`,
    `CREATE INDEX IF NOT EXISTS "ArenaMatch_ticketId_idx" ON "ArenaMatch"("ticketId");`,
    `CREATE INDEX IF NOT EXISTS "ArenaMatch_makerWallet_createdAt_idx" ON "ArenaMatch"("makerWallet", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "ArenaMatch_takerWallet_createdAt_idx" ON "ArenaMatch"("takerWallet", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "ArenaMatch_escrowPda_idx" ON "ArenaMatch"("escrowPda");`,
    `ALTER TABLE "ArenaMatch" ADD COLUMN IF NOT EXISTS "makerPositionId" TEXT;`,
    `ALTER TABLE "ArenaMatch" ADD COLUMN IF NOT EXISTS "takerPositionId" TEXT;`,
    `ALTER TABLE "ArenaMatch" ADD COLUMN IF NOT EXISTS "makerSide" TEXT;`,
    `ALTER TABLE "ArenaMatch" ADD COLUMN IF NOT EXISTS "stakeLamports" TEXT;`,
    `ALTER TABLE "ArenaMatch" ADD COLUMN IF NOT EXISTS "makerVaultPda" TEXT;`,
    `ALTER TABLE "ArenaMatch" ADD COLUMN IF NOT EXISTS "takerVaultPda" TEXT;`,
    `ALTER TABLE "ArenaMatch" ADD COLUMN IF NOT EXISTS "matchCommitTx" TEXT;`,
    `CREATE INDEX IF NOT EXISTS "ArenaMatch_makerPositionId_idx" ON "ArenaMatch"("makerPositionId");`,
    `CREATE INDEX IF NOT EXISTS "ArenaMatch_takerPositionId_idx" ON "ArenaMatch"("takerPositionId");`,
    `CREATE TABLE IF NOT EXISTS "SportPosition" (
        "id" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "selection" TEXT NOT NULL,
        "side" TEXT NOT NULL,
        "stakeLamports" TEXT NOT NULL,
        "filledLamports" TEXT NOT NULL DEFAULT '0',
        "remainingLamports" TEXT NOT NULL DEFAULT '0',
        "refundedLamports" TEXT NOT NULL DEFAULT '0',
        "vaultVersion" TEXT NOT NULL DEFAULT 'v2',
        "agentWallet" TEXT NOT NULL,
        "status" TEXT NOT NULL DEFAULT 'funding_required',
        "vaultPda" TEXT,
        "fundingTx" TEXT,
        "fundedLamports" TEXT,
        "fundedAt" TIMESTAMP(3),
        "fundingExpiresAt" TIMESTAMP(3),
        "cancelTx" TEXT,
        "matchedAt" TIMESTAMP(3),
        "matchedPositionId" TEXT,
        "matchId" TEXT,
        "offerId" TEXT,
        "ticketId" TEXT,
        "expiresAt" TIMESTAMP(3) NOT NULL,
        "clientOrderId" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "SportPosition_pkey" PRIMARY KEY ("id")
    );`,
    `ALTER TABLE "SportPosition" ALTER COLUMN "status" SET DEFAULT 'funding_required';`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "filledLamports" TEXT;`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "remainingLamports" TEXT;`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "refundedLamports" TEXT;`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "vaultVersion" TEXT;`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "vaultPda" TEXT;`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "fundingTx" TEXT;`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "fundedLamports" TEXT;`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "fundedAt" TIMESTAMP(3);`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "fundingExpiresAt" TIMESTAMP(3);`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "cancelTx" TEXT;`,
    `ALTER TABLE "SportPosition" ADD COLUMN IF NOT EXISTS "matchedAt" TIMESTAMP(3);`,
    `UPDATE "SportPosition"
     SET
        "filledLamports" = COALESCE(NULLIF("filledLamports", ''), '0'),
        "remainingLamports" = CASE
            WHEN "status" IN ('funded_open', 'matching') THEN COALESCE(NULLIF("remainingLamports", ''), "stakeLamports")
            WHEN "status" IN ('matched', 'filled') THEN COALESCE(NULLIF("remainingLamports", ''), '0')
            ELSE COALESCE(NULLIF("remainingLamports", ''), '0')
        END,
        "refundedLamports" = COALESCE(NULLIF("refundedLamports", ''), '0'),
        "vaultVersion" = CASE
            WHEN COALESCE(NULLIF("vaultVersion", ''), '') = '' THEN 'v1'
            ELSE "vaultVersion"
        END;`,
    `ALTER TABLE "SportPosition" ALTER COLUMN "filledLamports" SET DEFAULT '0';`,
    `ALTER TABLE "SportPosition" ALTER COLUMN "filledLamports" SET NOT NULL;`,
    `ALTER TABLE "SportPosition" ALTER COLUMN "remainingLamports" SET DEFAULT '0';`,
    `ALTER TABLE "SportPosition" ALTER COLUMN "remainingLamports" SET NOT NULL;`,
    `ALTER TABLE "SportPosition" ALTER COLUMN "refundedLamports" SET DEFAULT '0';`,
    `ALTER TABLE "SportPosition" ALTER COLUMN "refundedLamports" SET NOT NULL;`,
    `ALTER TABLE "SportPosition" ALTER COLUMN "vaultVersion" SET DEFAULT 'v2';`,
    `ALTER TABLE "SportPosition" ALTER COLUMN "vaultVersion" SET NOT NULL;`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "SportPosition_agentWallet_clientOrderId_key" ON "SportPosition"("agentWallet", "clientOrderId");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_fixtureId_status_stakeLamports_createdAt_idx" ON "SportPosition"("fixtureId", "status", "stakeLamports", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_fixtureId_selection_side_status_fundedAt_idx" ON "SportPosition"("fixtureId", "selection", "side", "status", "fundedAt");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_fixtureId_selection_side_status_remainingLamports_idx" ON "SportPosition"("fixtureId", "selection", "side", "status", "remainingLamports");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_agentWallet_status_createdAt_idx" ON "SportPosition"("agentWallet", "status", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_expiresAt_status_idx" ON "SportPosition"("expiresAt", "status");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_matchId_idx" ON "SportPosition"("matchId");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_offerId_idx" ON "SportPosition"("offerId");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_ticketId_idx" ON "SportPosition"("ticketId");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_vaultPda_idx" ON "SportPosition"("vaultPda");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_vaultVersion_idx" ON "SportPosition"("vaultVersion");`,
    `CREATE INDEX IF NOT EXISTS "SportPosition_fundedAt_idx" ON "SportPosition"("fundedAt");`,
    `CREATE TABLE IF NOT EXISTS "SportPositionFill" (
        "id" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "selection" TEXT NOT NULL,
        "backPositionId" TEXT NOT NULL,
        "layPositionId" TEXT NOT NULL,
        "backWallet" TEXT NOT NULL,
        "layWallet" TEXT NOT NULL,
        "fillLamports" TEXT NOT NULL,
        "ticketId" TEXT,
        "escrowPda" TEXT,
        "commitTx" TEXT,
        "status" TEXT NOT NULL DEFAULT 'committing',
        "winnerWallet" TEXT,
        "releaseTx" TEXT,
        "refundTx" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "settledAt" TIMESTAMP(3),
        CONSTRAINT "SportPositionFill_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE INDEX IF NOT EXISTS "SportPositionFill_fixtureId_status_createdAt_idx" ON "SportPositionFill"("fixtureId", "status", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "SportPositionFill_backPositionId_createdAt_idx" ON "SportPositionFill"("backPositionId", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "SportPositionFill_layPositionId_createdAt_idx" ON "SportPositionFill"("layPositionId", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "SportPositionFill_ticketId_idx" ON "SportPositionFill"("ticketId");`,
    `CREATE INDEX IF NOT EXISTS "SportPositionFill_status_createdAt_idx" ON "SportPositionFill"("status", "createdAt");`,
    `CREATE TABLE IF NOT EXISTS "SportPositionFundingEvent" (
        "id" TEXT NOT NULL,
        "positionId" TEXT NOT NULL,
        "wallet" TEXT NOT NULL,
        "event" TEXT NOT NULL,
        "txSignature" TEXT,
        "lamports" TEXT,
        "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "SportPositionFundingEvent_pkey" PRIMARY KEY ("id")
    );`,
    `CREATE INDEX IF NOT EXISTS "SportPositionFundingEvent_positionId_createdAt_idx" ON "SportPositionFundingEvent"("positionId", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "SportPositionFundingEvent_wallet_createdAt_idx" ON "SportPositionFundingEvent"("wallet", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "SportPositionFundingEvent_event_createdAt_idx" ON "SportPositionFundingEvent"("event", "createdAt");`,
    `CREATE TABLE IF NOT EXISTS "SportIntent" (
        "id" TEXT NOT NULL,
        "wallet" TEXT NOT NULL,
        "fixtureId" TEXT NOT NULL,
        "marketType" TEXT NOT NULL DEFAULT '1X2_PARTICIPANT_RESULT',
        "selection" TEXT NOT NULL,
        "side" TEXT NOT NULL,
        "stakeLamports" TEXT,
        "minStakeLamports" TEXT,
        "maxStakeLamports" TEXT,
        "status" TEXT NOT NULL DEFAULT 'active',
        "note" TEXT,
        "clientIntentId" TEXT,
        "expiresAt" TIMESTAMP(3),
        "lastNotifiedAt" TIMESTAMP(3),
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "SportIntent_pkey" PRIMARY KEY ("id")
    );`,
    `ALTER TABLE "SportIntent" ADD COLUMN IF NOT EXISTS "marketType" TEXT NOT NULL DEFAULT '1X2_PARTICIPANT_RESULT';`,
    `ALTER TABLE "SportIntent" ADD COLUMN IF NOT EXISTS "stakeLamports" TEXT;`,
    `ALTER TABLE "SportIntent" ADD COLUMN IF NOT EXISTS "minStakeLamports" TEXT;`,
    `ALTER TABLE "SportIntent" ADD COLUMN IF NOT EXISTS "maxStakeLamports" TEXT;`,
    `ALTER TABLE "SportIntent" ADD COLUMN IF NOT EXISTS "note" TEXT;`,
    `ALTER TABLE "SportIntent" ADD COLUMN IF NOT EXISTS "clientIntentId" TEXT;`,
    `ALTER TABLE "SportIntent" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);`,
    `ALTER TABLE "SportIntent" ADD COLUMN IF NOT EXISTS "lastNotifiedAt" TIMESTAMP(3);`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "SportIntent_wallet_clientIntentId_key" ON "SportIntent"("wallet", "clientIntentId");`,
    `CREATE INDEX IF NOT EXISTS "SportIntent_fixtureId_selection_side_status_createdAt_idx" ON "SportIntent"("fixtureId", "selection", "side", "status", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "SportIntent_wallet_status_createdAt_idx" ON "SportIntent"("wallet", "status", "createdAt");`,
    `CREATE INDEX IF NOT EXISTS "SportIntent_expiresAt_status_idx" ON "SportIntent"("expiresAt", "status");`,
];

export async function ensureApiSchema(
    prisma: PrismaClient,
    logger: LoggerLike = defaultLogger
): Promise<void> {
    try {
        for (const statement of DDL_STATEMENTS) {
            await prisma.$executeRawUnsafe(statement);
        }

        logger.info('api_schema_ready', {
            tables: [
                'Offer',
                'Ticket',
                'Agent',
                'AgentEvent',
                'AgentNotificationChannel',
                'AgentStrategyTemplate',
                'ArenaFixture',
                'ArenaOddsUpdate',
                'ArenaScoreUpdate',
                'ArenaTimelineEvent',
                'ArenaStrategySignal',
                'ArenaStrategyOffer',
                'ArenaOutcome',
                'ArenaMatch',
                'SportPosition',
                'SportPositionFill',
                'SportPositionFundingEvent',
                'SportIntent',
            ],
            columns: [
                'Offer.creatorSettlementWallet',
                'Offer.creatorRewardWallet',
                'Offer.creatorFundingWallet',
                'Offer.rollupMode',
                'Offer.fixtureId',
                'Offer.marketType',
                'Offer.selection',
                'Ticket.rollupMode',
                'Agent.webhookEvents',
                'AgentEvent.wallet',
                'AgentEvent.event',
                'AgentEvent.payload',
                'AgentEvent.ackedAt',
                'AgentNotificationChannel.wallet',
                'AgentNotificationChannel.type',
                'AgentNotificationChannel.config',
                'AgentStrategyTemplate.wallet',
                'AgentStrategyTemplate.name',
                'AgentStrategyTemplate.defaults',
                'ArenaFixture.fixtureId',
                'ArenaOddsUpdate.odds',
                'ArenaScoreUpdate.homeScore',
                'ArenaTimelineEvent.txlineTimestamp',
                'ArenaTimelineEvent.sourceEndpoint',
                'ArenaStrategySignal.fixtureId',
                'ArenaStrategySignal.tradeIntent',
                'ArenaStrategyOffer.signalId',
                'ArenaStrategyOffer.offerId',
                'ArenaOutcome.fixtureId',
                'ArenaOutcome.winner',
                'ArenaMatch.fixtureId',
                'ArenaMatch.offerId',
                'ArenaMatch.ticketId',
                'ArenaMatch.escrowPda',
                'ArenaMatch.settlementAction',
                'ArenaMatch.makerPositionId',
                'ArenaMatch.takerPositionId',
                'ArenaMatch.makerSide',
                'ArenaMatch.stakeLamports',
                'ArenaMatch.makerVaultPda',
                'ArenaMatch.takerVaultPda',
                'ArenaMatch.matchCommitTx',
                'SportPosition.fixtureId',
                'SportPosition.stakeLamports',
                'SportPosition.filledLamports',
                'SportPosition.remainingLamports',
                'SportPosition.refundedLamports',
                'SportPosition.vaultVersion',
                'SportPosition.vaultPda',
                'SportPosition.fundedAt',
                'SportPositionFill.fillLamports',
                'SportPositionFill.ticketId',
                'SportPositionFill.status',
                'SportPositionFundingEvent.positionId',
                'SportIntent.fixtureId',
                'SportIntent.status',
            ],
            mode: 'startup_self_heal',
        });
    } catch (error) {
        logger.error('api_schema_bootstrap_failed', {}, error);
        throw error;
    }
}
