use anchor_lang::prelude::*;
use ephemeral_rollups_sdk::access_control::instructions::{
    ClosePermissionCpiBuilder,
    CommitAndUndelegatePermissionCpiBuilder,
    CreatePermissionCpiBuilder,
    DelegatePermissionCpiBuilder,
};
use ephemeral_rollups_sdk::access_control::structs::{
    Member,
    MembersArgs,
    Permission,
    AUTHORITY_FLAG,
    TX_LOGS_FLAG,
    TX_MESSAGE_FLAG,
};
use ephemeral_rollups_sdk::anchor::{commit, delegate, ephemeral};
use ephemeral_rollups_sdk::delegate_args::DelegateAccounts;
use ephemeral_rollups_sdk::cpi::DelegateConfig;
use ephemeral_rollups_sdk::ephem::commit_and_undelegate_accounts;
use ephemeral_rollups_sdk::consts::{
    DELEGATION_PROGRAM_ID,
    MAGIC_CONTEXT_ID,
    MAGIC_PROGRAM_ID,
    PERMISSION_PROGRAM_ID,
};

declare_id!("BfFvxgysVSGdP2TwAjBRSFhDYtK2JA1VBd8BUqh8nGGq");

#[ephemeral]
#[program]
pub mod magicblock_negotiation {
    use super::*;

    /// 1. Create an on-chain Negotiation Session PDA.
    /// This account will be delegated to a MagicBlock ER/PER validator
    /// for sub-100ms state updates during the negotiation phase.
    pub fn initialize_session(
        ctx: Context<InitializeSession>,
        session_id: u64,
    ) -> Result<()> {
        let session = &mut ctx.accounts.session;
        session.session_id = session_id;
        session.buyer = ctx.accounts.buyer.key();
        session.agreed_price = 0;
        session.agreed_asset = String::new();
        session.buyer_collateral = 0;
        session.seller_collateral = 0;
        session.status = NegotiationStatus::Open;
        session.buyer_participant = Pubkey::default();
        session.seller_participant = Pubkey::default();
        session.terms_hash = [0; 32];
        session.buyer_payment_funding_hash = [0; 32];
        session.buyer_collateral_funding_hash = [0; 32];
        session.seller_collateral_funding_hash = [0; 32];
        session.buyer_collateral_ciphertext = Pubkey::default();
        session.seller_collateral_ciphertext = Pubkey::default();
        session.payment_amount_ciphertext = Pubkey::default();
        session.settlement_result_ciphertext = Pubkey::default();
        session.network_encryption_key = Pubkey::default();
        session.proof_recorded_at = 0;
        msg!(
            "Session {} created for buyer {}",
            session_id,
            session.buyer
        );
        Ok(())
    }

    /// 2. Delegate the Session PDA to a MagicBlock validator.
    /// The `#[delegate]` macro on `DelegateSession` auto-generates
    /// the `delegate_session` method which handles all CPI wiring —
    /// buffer creation, PDA signing, and delegation program invocation.
    pub fn delegate_session(ctx: Context<DelegateSession>) -> Result<()> {
        let session_id_bytes = ctx.accounts.session.session_id.to_le_bytes();

        let pda_seeds: &[&[u8]] = &[
            b"session",
            &session_id_bytes,
        ];

        let delegate_config = DelegateConfig {
            validator: ctx.accounts.validator.as_ref().map(|validator| validator.key()),
            ..DelegateConfig::default()
        };

        // Auto-generated by #[delegate] macro on the struct:
        ctx.accounts.delegate_session(
            &ctx.accounts.payer,
            pda_seeds,
            delegate_config,
        )?;

        msg!("Session delegated to MagicBlock ER");
        Ok(())
    }

    /// 2b. Create the PER permission account via on-chain CPI so the session
    /// PDA can sign with seeds.
    pub fn create_private_permission(
        ctx: Context<CreatePrivatePermission>,
        session_id: u64,
        buyer_member: Pubkey,
        seller_member: Pubkey,
    ) -> Result<()> {
        require!(
            ctx.accounts.permission_program.key() == PERMISSION_PROGRAM_ID,
            NegotiationError::InvalidPermissionProgram
        );

        let (expected_permission, _bump) = Permission::find_pda(&ctx.accounts.session.key());
        require!(
            ctx.accounts.permission.key() == expected_permission,
            NegotiationError::PermissionPdaMismatch
        );

        let members = MembersArgs {
            members: Some(vec![
                Member {
                    flags: AUTHORITY_FLAG,
                    pubkey: ctx.accounts.payer.key(),
                },
                Member {
                    flags: TX_MESSAGE_FLAG | TX_LOGS_FLAG,
                    pubkey: buyer_member,
                },
                Member {
                    flags: TX_MESSAGE_FLAG | TX_LOGS_FLAG,
                    pubkey: seller_member,
                },
            ]),
        };

        let session_id_bytes = session_id.to_le_bytes();
        let bump = [ctx.bumps.session];
        let signer_seeds: &[&[u8]] = &[b"session", &session_id_bytes, &bump];

        let permission_program = ctx.accounts.permission_program.to_account_info();
        let permission_account = ctx.accounts.permission.to_account_info();

        CreatePermissionCpiBuilder::new(&permission_program)
            .permissioned_account(&ctx.accounts.session.to_account_info())
            .permission(&permission_account)
            .payer(&ctx.accounts.payer.to_account_info())
            .system_program(&ctx.accounts.system_program.to_account_info())
            .args(members)
            .invoke_signed(&[signer_seeds])?;

        msg!(
            "Permission created for session {} with buyer {} and seller {}",
            session_id,
            buyer_member,
            seller_member
        );

        Ok(())
    }

    /// 2c. Delegate the PER permission account via on-chain CPI so the session
    /// PDA can sign with seeds during permission activation.
    pub fn delegate_private_permission<'info>(
        ctx: Context<'_, '_, '_, 'info, DelegatePrivatePermission<'info>>,
        session_id: u64,
    ) -> Result<()> {
        validate_private_permission_accounts(
            session_id,
            &ctx.accounts.session,
            &ctx.accounts.permission,
            &ctx.accounts.permission_program,
        )?;
        validate_delegate_private_permission_accounts(
            &ctx.accounts.permission,
            &ctx.accounts.delegation_buffer,
            &ctx.accounts.delegation_record,
            &ctx.accounts.delegation_metadata,
            &ctx.accounts.delegation_program,
        )?;

        let session_id_bytes = session_id.to_le_bytes();
        let bump = [ctx.bumps.session];
        let signer_seeds: &[&[u8]] = &[b"session", &session_id_bytes, &bump];

        let permission_program = ctx.accounts.permission_program.to_account_info();
        let payer = ctx.accounts.payer.to_account_info();
        let session = ctx.accounts.session.to_account_info();
        let permission = ctx.accounts.permission.to_account_info();
        let system_program = ctx.accounts.system_program.to_account_info();
        let delegation_buffer = ctx.accounts.delegation_buffer.to_account_info();
        let delegation_record = ctx.accounts.delegation_record.to_account_info();
        let delegation_metadata = ctx.accounts.delegation_metadata.to_account_info();
        let delegation_program = ctx.accounts.delegation_program.to_account_info();
        let validator = ctx.accounts.validator.to_account_info();

        let mut builder =
            DelegatePermissionCpiBuilder::new(&permission_program);
        builder
            .payer(&payer)
            .authority(&payer, false)
            .permissioned_account(&session, true)
            .permission(&permission)
            .system_program(&system_program)
            .owner_program(&permission_program)
            .delegation_buffer(&delegation_buffer)
            .delegation_record(&delegation_record)
            .delegation_metadata(&delegation_metadata)
            .delegation_program(&delegation_program)
            .validator(Some(&validator));

        for account in ctx.remaining_accounts.iter() {
            builder.add_remaining_account(account, account.is_writable, account.is_signer);
        }

        builder.invoke_signed(&[signer_seeds])?;

        msg!("Delegated PER permission for session {}", session_id);
        Ok(())
    }

    /// 3. Update negotiation terms (runs at sub-100ms on the ephemeral validator).
    /// Called via ER RPC. The `agreed_asset` string is capped at 64 chars.
    pub fn negotiate_terms(
        ctx: Context<NegotiateTerms>,
        new_price: u64,
        new_asset: String,
        new_buyer_collateral: u64,
        new_seller_collateral: u64,
    ) -> Result<()> {
        // Item 3 fix: cap string at 64 chars to prevent account overflow
        require!(
            new_asset.len() <= 64,
            NegotiationError::AssetNameTooLong
        );

        let session = &mut ctx.accounts.session;
        session.agreed_price = new_price;
        session.agreed_asset = new_asset;
        session.buyer_collateral = new_buyer_collateral;
        session.seller_collateral = new_seller_collateral;
        msg!(
            "Session {} updated: price={}, asset={}, buyer_collateral={}, seller_collateral={}",
            session.session_id,
            session.agreed_price,
            session.agreed_asset,
            session.buyer_collateral,
            session.seller_collateral,
        );
        Ok(())
    }

    /// 4. PER-only safety step: scrub negotiated terms before any final L1 sync.
    ///
    /// This keeps the delegated session usable as a coordination record while
    /// removing sensitive price/collateral fields before the permission program
    /// commits the account back to Solana during the Encrypt handoff.
    pub fn prepare_private_handoff(
        ctx: Context<PreparePrivateHandoff>,
        session_id: u64,
    ) -> Result<()> {
        let session = &mut ctx.accounts.session;
        require!(
            session.session_id == session_id,
            NegotiationError::SessionIdMismatch
        );

        session.agreed_price = 0;
        session.agreed_asset = String::new();
        session.buyer_collateral = 0;
        session.seller_collateral = 0;
        session.status = NegotiationStatus::ConfidentialHandoff;

        msg!(
            "Session {} scrubbed for confidential handoff by {}",
            session.session_id,
            ctx.accounts.payer.key()
        );

        Ok(())
    }

    /// 4a. Record the canonical confidential handoff proof directly inside the
    /// delegated session PDA while it is still running on the attested TEE.
    ///
    /// This makes the session PDA itself the source of truth for:
    /// - the real counterparties
    /// - the hashed negotiated terms
    /// - the Encrypt ciphertext accounts that downstream escrow will use
    ///
    /// The plaintext negotiation fields are scrubbed in the same state
    /// transition so the session can later be committed back to L1 without
    /// exposing price/collateral terms.
    pub fn record_private_handoff_proof(
        ctx: Context<RecordPrivateHandoffProof>,
        session_id: u64,
        buyer_participant: Pubkey,
        seller_participant: Pubkey,
        terms_hash: [u8; 32],
        buyer_payment_funding_hash: [u8; 32],
        buyer_collateral_funding_hash: [u8; 32],
        seller_collateral_funding_hash: [u8; 32],
        buyer_collateral_ciphertext: Pubkey,
        seller_collateral_ciphertext: Pubkey,
        payment_amount_ciphertext: Pubkey,
        settlement_result_ciphertext: Pubkey,
        network_encryption_key: Pubkey,
    ) -> Result<()> {
        let session = &mut ctx.accounts.session;
        require!(
            session.session_id == session_id,
            NegotiationError::SessionIdMismatch
        );
        require!(
            buyer_participant != Pubkey::default() &&
            seller_participant != Pubkey::default() &&
            buyer_participant != seller_participant,
            NegotiationError::InvalidCounterparties
        );
        require!(
            terms_hash.iter().any(|byte| *byte != 0),
            NegotiationError::MissingPrivateHandoffProof
        );
        require!(
            buyer_payment_funding_hash.iter().any(|byte| *byte != 0) &&
            buyer_collateral_funding_hash.iter().any(|byte| *byte != 0) &&
            seller_collateral_funding_hash.iter().any(|byte| *byte != 0),
            NegotiationError::MissingPrivateHandoffProof
        );
        require!(
            buyer_collateral_ciphertext != Pubkey::default() &&
            seller_collateral_ciphertext != Pubkey::default() &&
            payment_amount_ciphertext != Pubkey::default() &&
            settlement_result_ciphertext != Pubkey::default() &&
            network_encryption_key != Pubkey::default(),
            NegotiationError::InvalidCiphertextHandle
        );

        session.buyer_participant = buyer_participant;
        session.seller_participant = seller_participant;
        session.terms_hash = terms_hash;
        session.buyer_payment_funding_hash = buyer_payment_funding_hash;
        session.buyer_collateral_funding_hash = buyer_collateral_funding_hash;
        session.seller_collateral_funding_hash = seller_collateral_funding_hash;
        session.buyer_collateral_ciphertext = buyer_collateral_ciphertext;
        session.seller_collateral_ciphertext = seller_collateral_ciphertext;
        session.payment_amount_ciphertext = payment_amount_ciphertext;
        session.settlement_result_ciphertext = settlement_result_ciphertext;
        session.network_encryption_key = network_encryption_key;
        session.proof_recorded_at = Clock::get()?.unix_timestamp;

        session.agreed_price = 0;
        session.agreed_asset = String::new();
        session.buyer_collateral = 0;
        session.seller_collateral = 0;
        session.status = NegotiationStatus::ConfidentialHandoff;

        msg!(
            "Session {} recorded confidential handoff proof for buyer {} and seller {}",
            session.session_id,
            session.buyer_participant,
            session.seller_participant
        );

        Ok(())
    }

    /// 4b. Commit the scrubbed PER session back to L1 through the permission
    /// program, with the session PDA signing via seeds.
    pub fn commit_private_permission<'info>(
        ctx: Context<'_, '_, '_, 'info, CommitPrivatePermission<'info>>,
        session_id: u64,
    ) -> Result<()> {
        validate_private_permission_accounts(
            session_id,
            &ctx.accounts.session,
            &ctx.accounts.permission,
            &ctx.accounts.permission_program,
        )?;

        let session_id_bytes = session_id.to_le_bytes();
        let bump = [ctx.bumps.session];
        let signer_seeds: &[&[u8]] = &[b"session", &session_id_bytes, &bump];

        let permission_program = ctx.accounts.permission_program.to_account_info();
        let payer = ctx.accounts.payer.to_account_info();
        let session = ctx.accounts.session.to_account_info();
        let permission = ctx.accounts.permission.to_account_info();
        let magic_program = ctx.accounts.magic_program.to_account_info();
        let magic_context = ctx.accounts.magic_context.to_account_info();

        commit_and_undelegate_accounts(
            &payer,
            vec![&session],
            &magic_context,
            &magic_program,
            None,
        )?;

        let mut builder =
            CommitAndUndelegatePermissionCpiBuilder::new(&permission_program);
        builder
            .authority(&payer, true)
            .permissioned_account(&session, true)
            .permission(&permission)
            .magic_program(&magic_program)
            .magic_context(&magic_context);

        for account in ctx.remaining_accounts.iter() {
            builder.add_remaining_account(account, account.is_writable, account.is_signer);
        }

        builder.invoke_signed(&[signer_seeds])?;

        msg!("Committed scrubbed PER session {} back to L1", session_id);
        Ok(())
    }

    /// 4c. Close the PER permission account after it has been undelegated.
    pub fn close_private_permission<'info>(
        ctx: Context<'_, '_, '_, 'info, ClosePrivatePermission<'info>>,
        session_id: u64,
    ) -> Result<()> {
        validate_private_permission_accounts(
            session_id,
            &ctx.accounts.session,
            &ctx.accounts.permission,
            &ctx.accounts.permission_program,
        )?;

        let session_id_bytes = session_id.to_le_bytes();
        let bump = [ctx.bumps.session];
        let signer_seeds: &[&[u8]] = &[b"session", &session_id_bytes, &bump];

        let permission_program = ctx.accounts.permission_program.to_account_info();
        let payer = ctx.accounts.payer.to_account_info();
        let session = ctx.accounts.session.to_account_info();
        let permission = ctx.accounts.permission.to_account_info();

        let mut builder =
            ClosePermissionCpiBuilder::new(&permission_program);
        builder
            .payer(&payer)
            .authority(&payer, false)
            .permissioned_account(&session, true)
            .permission(&permission);

        for account in ctx.remaining_accounts.iter() {
            builder.add_remaining_account(account, account.is_writable, account.is_signer);
        }

        builder.invoke_signed(&[signer_seeds])?;

        msg!("Closed PER permission for session {}", session_id);
        Ok(())
    }

    /// 5. Mark consensus and commit+undelegate — commits state back to Solana L1.
    /// Uses `commit_and_undelegate_accounts` from the SDK's `ephem` module,
    /// which routes through the Magic Program (no raw buffer/signer required).
    pub fn reach_consensus(
        ctx: Context<ReachConsensus>,
        session_id: u64,
    ) -> Result<()> {
        msg!(
            "Session consensus reached. Committing + undelegating."
        );

        let mut session = load_session(&ctx.accounts.session)?;
        require!(
            session.session_id == session_id,
            NegotiationError::SessionIdMismatch
        );
        session.status = NegotiationStatus::ConsensusReached;
        store_session(&ctx.accounts.session, &session)?;

        // SDK ephem::commit_and_undelegate_accounts routes through the Magic Program.
        commit_and_undelegate_accounts(
            &ctx.accounts.payer.to_account_info(),          // payer
            vec![&ctx.accounts.session.to_account_info()],  // accounts to undelegate
            &ctx.accounts.magic_context,                    // magic_context
            &ctx.accounts.magic_program,                    // magic_program
            None,                                            // magic_fee_vault
        )?;

        Ok(())
    }
}

// ══════════════════════════════════════════════════════════════════════
// ACCOUNTS
// ══════════════════════════════════════════════════════════════════════

#[derive(Accounts)]
#[instruction(session_id: u64)]
pub struct InitializeSession<'info> {
    #[account(
        init,
        payer = buyer,
        space = 8 + Session::LEN,
        seeds = [b"session", session_id.to_le_bytes().as_ref()],
        bump
    )]
    pub session: Account<'info, Session>,
    #[account(mut)]
    pub buyer: Signer<'info>,
    pub system_program: Program<'info, System>,
}

/// The `#[delegate]` macro processes the `#[account(mut, del)]` tag on `session`.
/// It auto-generates buffer, delegation_record, delegation_metadata PDAs,
/// and a `delegate_session(&self, payer, seeds, config)` method.
#[delegate]
#[derive(Accounts)]
pub struct DelegateSession<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    /// CHECK: Optional explicit validator identity account for PER/ER routing.
    pub validator: Option<AccountInfo<'info>>,
    #[account(mut, del)]
    pub session: Account<'info, Session>,
}

#[derive(Accounts)]
#[instruction(session_id: u64)]
pub struct CreatePrivatePermission<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(
        seeds = [b"session", session_id.to_le_bytes().as_ref()],
        bump
    )]
    pub session: Account<'info, Session>,
    /// CHECK: Permission PDA validated against the session account
    #[account(mut)]
    pub permission: UncheckedAccount<'info>,
    /// CHECK: Verified against MagicBlock permission program id
    pub permission_program: UncheckedAccount<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(session_id: u64)]
pub struct DelegatePrivatePermission<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    /// CHECK: Session PDA is validated by seeds and by explicit permission PDA checks.
    #[account(
        seeds = [b"session", session_id.to_le_bytes().as_ref()],
        bump
    )]
    pub session: UncheckedAccount<'info>,
    /// CHECK: Permission PDA validated against the session account
    #[account(mut)]
    pub permission: UncheckedAccount<'info>,
    /// CHECK: Verified against MagicBlock permission program id
    #[account(address = PERMISSION_PROGRAM_ID)]
    pub permission_program: UncheckedAccount<'info>,
    pub system_program: Program<'info, System>,
    /// CHECK: Derived from the permission PDA and the permission program
    #[account(mut)]
    pub delegation_buffer: UncheckedAccount<'info>,
    /// CHECK: Derived from the permission PDA
    #[account(mut)]
    pub delegation_record: UncheckedAccount<'info>,
    /// CHECK: Derived from the permission PDA
    #[account(mut)]
    pub delegation_metadata: UncheckedAccount<'info>,
    /// CHECK: Verified against MagicBlock delegation program id
    #[account(address = DELEGATION_PROGRAM_ID)]
    pub delegation_program: UncheckedAccount<'info>,
    /// CHECK: Validator identity is resolved by the caller
    pub validator: UncheckedAccount<'info>,
}

#[derive(Accounts)]
pub struct NegotiateTerms<'info> {
    #[account(mut)]
    pub session: Account<'info, Session>,
}

#[derive(Accounts)]
#[instruction(session_id: u64)]
pub struct PreparePrivateHandoff<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(
        mut,
        seeds = [b"session", session_id.to_le_bytes().as_ref()],
        bump
    )]
    pub session: Account<'info, Session>,
}

#[derive(Accounts)]
#[instruction(session_id: u64)]
pub struct RecordPrivateHandoffProof<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(
        mut,
        seeds = [b"session", session_id.to_le_bytes().as_ref()],
        bump
    )]
    pub session: Account<'info, Session>,
}

#[derive(Accounts)]
#[instruction(session_id: u64)]
pub struct CommitPrivatePermission<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    /// CHECK: Session PDA is validated by seeds and by explicit permission PDA checks.
    #[account(
        mut,
        seeds = [b"session", session_id.to_le_bytes().as_ref()],
        bump
    )]
    pub session: UncheckedAccount<'info>,
    /// CHECK: Permission PDA validated against the session account
    #[account(mut)]
    pub permission: UncheckedAccount<'info>,
    /// CHECK: Verified against MagicBlock permission program id
    #[account(address = PERMISSION_PROGRAM_ID)]
    pub permission_program: UncheckedAccount<'info>,
    /// CHECK: Verified against MagicBlock magic program id
    #[account(address = MAGIC_PROGRAM_ID)]
    pub magic_program: UncheckedAccount<'info>,
    /// CHECK: Verified against MagicBlock magic context id
    #[account(mut, address = MAGIC_CONTEXT_ID)]
    pub magic_context: UncheckedAccount<'info>,
}

#[derive(Accounts)]
#[instruction(session_id: u64)]
pub struct ClosePrivatePermission<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    /// CHECK: Session PDA is validated by seeds and by explicit permission PDA checks.
    #[account(
        seeds = [b"session", session_id.to_le_bytes().as_ref()],
        bump
    )]
    pub session: UncheckedAccount<'info>,
    /// CHECK: Permission PDA validated against the session account
    #[account(mut)]
    pub permission: UncheckedAccount<'info>,
    /// CHECK: Verified against MagicBlock permission program id
    #[account(address = PERMISSION_PROGRAM_ID)]
    pub permission_program: UncheckedAccount<'info>,
}

#[commit]
#[derive(Accounts)]
#[instruction(session_id: u64)]
pub struct ReachConsensus<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    /// CHECK: PDA is validated by seeds; data is deserialized manually because
    /// the delegated account is temporarily owned by the delegation program.
    #[account(
        mut,
        seeds = [b"session", session_id.to_le_bytes().as_ref()],
        bump
    )]
    pub session: UncheckedAccount<'info>,
}

// ══════════════════════════════════════════════════════════════════════
// STATE
// ══════════════════════════════════════════════════════════════════════

#[account]
pub struct Session {
    pub session_id: u64,
    pub buyer: Pubkey,
    pub agreed_price: u64,
    pub agreed_asset: String,
    pub buyer_collateral: u64,
    pub seller_collateral: u64,
    pub status: NegotiationStatus,
    pub buyer_participant: Pubkey,
    pub seller_participant: Pubkey,
    pub terms_hash: [u8; 32],
    pub buyer_payment_funding_hash: [u8; 32],
    pub buyer_collateral_funding_hash: [u8; 32],
    pub seller_collateral_funding_hash: [u8; 32],
    pub buyer_collateral_ciphertext: Pubkey,
    pub seller_collateral_ciphertext: Pubkey,
    pub payment_amount_ciphertext: Pubkey,
    pub settlement_result_ciphertext: Pubkey,
    pub network_encryption_key: Pubkey,
    pub proof_recorded_at: i64,
}

impl Session {
    // 8 (id)
    // + 32 (session creator / payer)
    // + 8 (price)
    // + 4+64 (asset string)
    // + 8 (buyer collateral)
    // + 8 (seller collateral)
    // + 1 (status)
    // + 32 (buyer participant)
    // + 32 (seller participant)
    // + 32 (terms hash)
    // + 32 (buyer payment funding hash)
    // + 32 (buyer collateral funding hash)
    // + 32 (seller collateral funding hash)
    // + 32 (buyer collateral ciphertext account)
    // + 32 (seller collateral ciphertext account)
    // + 32 (payment amount ciphertext account)
    // + 32 (settlement result ciphertext account)
    // + 32 (network encryption key PDA)
    // + 8 (proof recorded at unix timestamp)
    pub const LEN: usize = 8 + 32 + 8 + (4 + 64) + 8 + 8 + 1 + 32 + 32 + 32 + 32 + 32 + 32 + 32 + 32 + 32 + 32 + 8;
}

fn load_session(account: &UncheckedAccount) -> Result<Session> {
    let session_data = account.try_borrow_data()?;
    let mut session_bytes: &[u8] = &session_data[..];
    Session::try_deserialize(&mut session_bytes).map_err(Into::into)
}

fn store_session(account: &UncheckedAccount, session: &Session) -> Result<()> {
    let mut session_data = account.try_borrow_mut_data()?;
    let mut write_cursor = &mut session_data[..];
    session.try_serialize(&mut write_cursor)?;
    Ok(())
}

fn validate_private_permission_accounts(
    session_id: u64,
    session: &UncheckedAccount,
    permission: &UncheckedAccount,
    permission_program: &UncheckedAccount,
) -> Result<()> {
    require!(
        permission_program.key() == PERMISSION_PROGRAM_ID,
        NegotiationError::InvalidPermissionProgram
    );

    let (expected_session, _session_bump) =
        Pubkey::find_program_address(&[b"session", &session_id.to_le_bytes()], &crate::ID);
    require!(
        session.key() == expected_session,
        NegotiationError::SessionIdMismatch
    );

    let (expected_permission, _permission_bump) = Permission::find_pda(&session.key());
    require!(
        permission.key() == expected_permission,
        NegotiationError::PermissionPdaMismatch
    );

    Ok(())
}

fn validate_delegate_private_permission_accounts(
    permission: &UncheckedAccount,
    delegation_buffer: &UncheckedAccount,
    delegation_record: &UncheckedAccount,
    delegation_metadata: &UncheckedAccount,
    delegation_program: &UncheckedAccount,
) -> Result<()> {
    require!(
        delegation_program.key() == DELEGATION_PROGRAM_ID,
        NegotiationError::InvalidDelegationProgram
    );

    let delegate_accounts = DelegateAccounts::new(permission.key(), PERMISSION_PROGRAM_ID);
    require!(
        delegation_buffer.key() == delegate_accounts.delegate_buffer,
        NegotiationError::DelegationPdaMismatch
    );
    require!(
        delegation_record.key() == delegate_accounts.delegation_record,
        NegotiationError::DelegationPdaMismatch
    );
    require!(
        delegation_metadata.key() == delegate_accounts.delegation_metadata,
        NegotiationError::DelegationPdaMismatch
    );

    Ok(())
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone, PartialEq, Eq)]
pub enum NegotiationStatus {
    Open,
    ConsensusReached,
    Failed,
    ConfidentialHandoff,
}

// ══════════════════════════════════════════════════════════════════════
// ERRORS
// ══════════════════════════════════════════════════════════════════════

#[error_code]
pub enum NegotiationError {
    #[msg("Asset name exceeds 64 character limit")]
    AssetNameTooLong,
    #[msg("Session id did not match the provided session PDA")]
    SessionIdMismatch,
    #[msg("The provided permission PDA did not match the session account")]
    PermissionPdaMismatch,
    #[msg("The provided permission program was invalid")]
    InvalidPermissionProgram,
    #[msg("The provided delegation program was invalid")]
    InvalidDelegationProgram,
    #[msg("The provided delegation PDA did not match the permission account")]
    DelegationPdaMismatch,
    #[msg("The buyer and seller counterparties must be distinct non-default public keys")]
    InvalidCounterparties,
    #[msg("The private handoff proof must include a non-zero terms hash")]
    MissingPrivateHandoffProof,
    #[msg("The private handoff proof included an invalid ciphertext handle or network encryption key")]
    InvalidCiphertextHandle,
}
